// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ3mhhIvIzcm23ifB5t7yep1QCIWX3euA',
    appId: '1:229456712816:web:6afcfa57f982e253bd10b5',
    messagingSenderId: '229456712816',
    projectId: 'libreville-decouverte',
    authDomain: 'libreville-decouverte.firebaseapp.com',
    storageBucket: 'libreville-decouverte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBtnIufKvXsZnh6W2zT29z8pxxkydNgqo',
    appId: '1:229456712816:ios:d4b58d0dcaa031e1bd10b5',
    messagingSenderId: '229456712816',
    projectId: 'libreville-decouverte',
    storageBucket: 'libreville-decouverte.firebasestorage.app',
    iosBundleId: 'com.example.librevilleDecouverte',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBtnIufKvXsZnh6W2zT29z8pxxkydNgqo',
    appId: '1:229456712816:ios:d4b58d0dcaa031e1bd10b5',
    messagingSenderId: '229456712816',
    projectId: 'libreville-decouverte',
    storageBucket: 'libreville-decouverte.firebasestorage.app',
    iosBundleId: 'com.example.librevilleDecouverte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ3mhhIvIzcm23ifB5t7yep1QCIWX3euA',
    appId: '1:229456712816:web:cf4089f60100f5c5bd10b5',
    messagingSenderId: '229456712816',
    projectId: 'libreville-decouverte',
    authDomain: 'libreville-decouverte.firebaseapp.com',
    storageBucket: 'libreville-decouverte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZi9W_vCjwo012H4T_OAFPr4Z5GGKhG8',
    appId: '1:229456712816:android:35a8381de8c1ed47bd10b5',
    messagingSenderId: '229456712816',
    projectId: 'libreville-decouverte',
    storageBucket: 'libreville-decouverte.firebasestorage.app',
  );
}
